require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/watchshows", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Watchshow. As you add validations to Watchshow, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # WatchshowsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  # describe "GET /index" do
  #   it "renders a successful response" do
  #     Watchshow.create! valid_attributes
  #     get watchshows_url, headers: valid_headers, as: :json
  #     expect(response).to be_successful
  #   end
  # end

  # describe "GET /show" do
  #   it "renders a successful response" do
  #     watchshow = Watchshow.create! valid_attributes
  #     get watchshow_url(watchshow), as: :json
  #     expect(response).to be_successful
  #   end
  # end

  # describe "POST /create" do
  #   context "with valid parameters" do
  #     it "creates a new Watchshow" do
  #       expect {
  #         post watchshows_url,
  #              params: { watchshow: valid_attributes }, headers: valid_headers, as: :json
  #       }.to change(Watchshow, :count).by(1)
  #     end

  #     it "renders a JSON response with the new watchshow" do
  #       post watchshows_url,
  #            params: { watchshow: valid_attributes }, headers: valid_headers, as: :json
  #       expect(response).to have_http_status(:created)
  #       expect(response.content_type).to match(a_string_including("application/json"))
  #     end
  #   end

  #   context "with invalid parameters" do
  #     it "does not create a new Watchshow" do
  #       expect {
  #         post watchshows_url,
  #              params: { watchshow: invalid_attributes }, as: :json
  #       }.to change(Watchshow, :count).by(0)
  #     end

  #     it "renders a JSON response with errors for the new watchshow" do
  #       post watchshows_url,
  #            params: { watchshow: invalid_attributes }, headers: valid_headers, as: :json
  #       expect(response).to have_http_status(:unprocessable_entity)
  #       expect(response.content_type).to match(a_string_including("application/json"))
  #     end
  #   end
  # end

  # describe "PATCH /update" do
  #   context "with valid parameters" do
  #     let(:new_attributes) {
  #       skip("Add a hash of attributes valid for your model")
  #     }

  #     it "updates the requested watchshow" do
  #       watchshow = Watchshow.create! valid_attributes
  #       patch watchshow_url(watchshow),
  #             params: { watchshow: new_attributes }, headers: valid_headers, as: :json
  #       watchshow.reload
  #       skip("Add assertions for updated state")
  #     end

  #     it "renders a JSON response with the watchshow" do
  #       watchshow = Watchshow.create! valid_attributes
  #       patch watchshow_url(watchshow),
  #             params: { watchshow: new_attributes }, headers: valid_headers, as: :json
  #       expect(response).to have_http_status(:ok)
  #       expect(response.content_type).to match(a_string_including("application/json"))
  #     end
  #   end

  #   context "with invalid parameters" do
  #     it "renders a JSON response with errors for the watchshow" do
  #       watchshow = Watchshow.create! valid_attributes
  #       patch watchshow_url(watchshow),
  #             params: { watchshow: invalid_attributes }, headers: valid_headers, as: :json
  #       expect(response).to have_http_status(:unprocessable_entity)
  #       expect(response.content_type).to match(a_string_including("application/json"))
  #     end
  #   end
  # end

  # describe "DELETE /destroy" do
  #   it "destroys the requested watchshow" do
  #     watchshow = Watchshow.create! valid_attributes
  #     expect {
  #       delete watchshow_url(watchshow), headers: valid_headers, as: :json
  #     }.to change(Watchshow, :count).by(-1)
  #   end
  # end


  before(:each) do
    FactoryBot.create(:show, title: "DBZ")
    FactoryBot.create(:user, email: "Matilda@email.com", password: '123456', password_confirmation: '123456')
    FactoryBot.create(:watchlist, user_id: '1' )
    FactoryBot.create(:watchshow, show_id: '1', watchlist_id: '1')
  end

  describe "GET all watchshows at /watchshows" do
    it "returns all watchshows" do
      get "/watchshows"
      print response
      expect(response).to have_http_status(200)
    end
  end
end
